# ------------------------------------------------------------------------
# APPLICATION CONFIG
# ------------------------------------------------------------------------
# name - name used in site title and meta (string; optional)
# user_id - Spotify user ID (string)
# enable_all - import all user's public playlists (boolean)
# ------------------------------------------------------------------------

name: "bartosjiri"
user_id: "21gi2l2todfet7ujsdtofnn5y"
enable_all: true