# ------------------------------------------------------------------------
# APPLICATION CONFIG
# ------------------------------------------------------------------------
# domain: domain URL (string)
# ------------------------------------------------------------------------

domain: "https://mixtapes.bartosjiri.com"